// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  CloseParen = 2,
  OpenParen = 3,
  List = 4,
  CloseBracket = 5,
  OpenBracket = 6,
  Vector = 7,
  CloseBrace = 8,
  OpenBrace = 9,
  Map = 10,
  LineComment = 11,
  Number = 12,
  String = 13,
  Keyword = 14,
  BuiltinName = 15,
  Symbol = 16
