// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  List = 2,
  Vector = 3,
  Map = 4,
  LineComment = 5,
  Number = 6,
  String = 7,
  Keyword = 8,
  BuiltinName = 9,
  Symbol = 10
