[build]
  command = "curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh && npm run build:wasm && npx shadow-cljs release app"
  publish = "app/public"

[build.environment]
  NODE_VERSION = "20"
